### ISSUE TITLE
React\Dns\RecordNotFoundException not handled

### ISSUE THREAD

**Issue by elazar** [WyriHaximus/PhergieDns#3]
I was able to get this by trying to make an HTTP request from a plugin to localhost where there was no web server running. Seems like the Dns plugin should provide a request object with resolve and reject callbacks similar to how the Http plugin works?

```
2014-05-22 19:23:34 DEBUG [Http][537e9506b08b2]Error executing request: exception 'React\Dns\RecordNotFoundException' with message 'DNS Request did not return valid answer. Received answers: []' in test/vendor/react/dns/React/Dns/Resolver/Resolver.php:52
Stack trace:
#0 test/vendor/react/dns/React/Dns/Resolver/Resolver.php(36): React\Dns\Resolver\Resolver->pickRandomAnswerOfType(Object(React\Dns\Model\Message), 1)
#1 test/vendor/react/dns/React/Dns/Resolver/Resolver.php(30): React\Dns\Resolver\Resolver->extractAddress(Object(React\Dns\Model\Message), 1)
#2 [internal function]: React\Dns\Resolver\Resolver->React\Dns\Resolver\{closure}(Object(React\Dns\Model\Message))
#3 test/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Object(Closure), Object(React\Dns\Model\Message))
#4 test/vendor/react/promise/src/React/Promise/Deferred.php(39): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#5 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#6 test/vendor/react/promise/src/React/Promise/Deferred.php(102): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#7 test/vendor/react/promise/src/React/Promise/Deferred.php(60): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#8 [internal function]: React\Promise\Deferred->resolve(Object(React\Dns\Model\Message))
#9 test/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, Object(React\Dns\Model\Message))
#10 test/vendor/react/promise/src/React/Promise/Deferred.php(44): React\Promise\FulfilledPromise->then(Array, Array, Array)
#11 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#12 test/vendor/react/promise/src/React/Promise/Deferred.php(102): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#13 test/vendor/react/promise/src/React/Promise/Deferred.php(60): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#14 test/vendor/react/promise/src/React/Promise/DeferredResolver.php(16): React\Promise\Deferred->resolve(Object(React\Dns\Model\Message))
#15 [internal function]: React\Promise\DeferredResolver->resolve(Object(React\Dns\Model\Message))
#16 test/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, Object(React\Dns\Model\Message))
#17 test/vendor/react/promise/src/React/Promise/Deferred.php(39): React\Promise\FulfilledPromise->then(Array, Object(Closure))
#18 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#19 test/vendor/react/promise/src/React/Promise/Deferred.php(102): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#20 test/vendor/react/promise/src/React/Promise/Deferred.php(60): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#21 test/vendor/react/dns/React/Dns/Query/Executor.php(89): React\Promise\Deferred->resolve(Object(React\Dns\Model\Message))
#22 [internal function]: React\Dns\Query\Executor->React\Dns\Query\{closure}('X}???????????lo...', Object(React\Socket\Connection))
#23 test/vendor/evenement/evenement/src/Evenement/EventEmitter.php(70): call_user_func_array(Object(Closure), Array)
#24 test/vendor/react/socket/React/Socket/Connection.php(20): Evenement\EventEmitter->emit('data', Array)
#25 [internal function]: React\Socket\Connection->handleData(Resource id #86, Object(React\EventLoop\StreamSelectLoop))
#26 test/vendor/react/event-loop/React/EventLoop/StreamSelectLoop.php(145): call_user_func(Array, Resource id #86, Object(React\EventLoop\StreamSelectLoop))
#27 test/vendor/react/event-loop/React/EventLoop/StreamSelectLoop.php(165): React\EventLoop\StreamSelectLoop->runStreamSelect()
#28 test/vendor/react/event-loop/React/EventLoop/StreamSelectLoop.php(174): React\EventLoop\StreamSelectLoop->tick()
#29 test/vendor/phergie/phergie-irc-client-react/src/Client.php(464): React\EventLoop\StreamSelectLoop->run()
#30 test/vendor/phergie/phergie-irc-bot-react/src/Bot.php(234): Phergie\Irc\Client\React\Client->run(Array)
#31 test/vendor/phergie/phergie-irc-bot-react/bin/phergie(28): Phergie\Irc\Bot\React\Bot->run()
#32 {main}
```

**Comment by elazar** [comment]
*bum

**Comment by WyriHaximus** [comment]
Is this still an issue? DNS has a query object now and HTTP calls the reject callback when it fails.

**Comment by elazar** [comment]
Indeed, it does. Closing this out. Thanks.

**Comment by WyriHaximus** [comment]
Thanks :+1:
